FROM cypress/base:18.16.0

WORKDIR /test

RUN apt-get update && apt-get --assume-yes install curl jq

COPY . ./

RUN yarn install --production=false && yarn cache clean

RUN npx playwright install-deps webkit
RUN npx cypress verify
